/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import domain.Desenhista;
import edu.princeton.cs.algs4.Draw;

public class App {
    public static void main(String[] args) {
        info();
        aplicacao();
    }

    public static void info(){ //Informa o usuário de como o programa funciona

    }

    public static void aplicacao(){ //Roda a aplicação
        Desenhista desenhista = new Desenhista(); //Cria o nosso desenhista
        Draw ouvidor = new Draw();

        while(true){ //Permanece executando a aplicação até que o programa em si seja fechado

        }
    }
}