/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import domain.Desenhista;

public class App {
    public static void main(String[] args) {
        Desenhista desenhista = new Desenhista(); //Cria o desenhista
        desenhista.exibeTela(); //Exibe o quadro branco na tela



        System.out.println("A");
    }
}
